import { expect } from '@playwright/test';
import { test } from './fixture';
import { mcpServer } from './mcp-fixture';

test('connectors stay compact until opened and setup starts from Add', async ({ workspace }, info) => {
  const server = await mcpServer(true);
  const work = await workspace();
  let id: string | undefined;
  try {
    await work.page.getByRole('button', { name: 'Settings', exact: true }).click();
    await work.page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Connectors', exact: true }).click();
    await expect(work.page.getByLabel('MCP server URL')).toHaveCount(0);
    await work.page.getByRole('button', { name: 'Add connector', exact: true }).click();
    const add = work.page.getByRole('dialog', { name: 'Add connector', exact: true });
    await work.page.evaluate(() => window.dextana.setTheme('light'));
    await expect(add.getByRole('button', { name: 'Continue', exact: true })).toBeDisabled();
    const localButton = add.getByRole('button', { name: 'Connect a local tool', exact: true });
    expect(await localButton.evaluate(node => getComputedStyle(node).backgroundColor)).not.toBe(await add.evaluate(node => getComputedStyle(node).backgroundColor));
    await expect(add.getByRole('button', { name: 'Custom MCP', exact: true })).toHaveAttribute('aria-pressed', 'true');
    const addressBox = (await add.getByLabel('MCP server URL').boundingBox())!;
    const continueBox = (await add.getByRole('button', { name: 'Continue', exact: true }).boundingBox())!;
    expect(Math.abs(addressBox.y - continueBox.y)).toBeLessThan(1);
    expect(Math.abs(addressBox.height - continueBox.height)).toBeLessThan(1);
    await add.screenshot({ path: info.outputPath('connectors-add-light.png') });
    await add.getByLabel('MCP server URL').fill(server.url);
    await add.getByRole('button', { name: 'Continue', exact: true }).click();
    const connect = work.page.getByRole('dialog', { name: 'Connect MCP', exact: true });
    await connect.screenshot({ path: info.outputPath('connector-modal-card-fields.png') });
    await connect.getByLabel('MCP connection name').fill('Compact tasks');
    await connect.getByLabel('Auth token', { exact: true }).fill('synthetic-mcp-token');
    await connect.getByRole('button', { name: 'Connect', exact: true }).click();
    const tools = work.page.getByRole('dialog', { name: 'Choose tools', exact: true });
    await expect(tools).toBeVisible();
    const readCard = tools.getByRole('region', { name: 'read tasks', exact: true });
    await readCard.getByText('read tasks', { exact: true }).click();
    await expect(tools.getByLabel('Policy for read_tasks')).toHaveValue('ask');
    await readCard.getByLabel('Inputs for read_tasks').click();
    await expect(tools.getByRole('checkbox', { name: 'Enable tool read_tasks', exact: true })).toBeChecked();
    await tools.screenshot({ path: info.outputPath('shared-tool-checkbox-cards.png') });

    await tools.getByRole('button', { name: 'Close dialog' }).click();
    const row = work.page.getByRole('region', { name: 'MCP connection Compact tasks', exact: true });
    id = (await work.page.evaluate(() => window.dextana.snapshot())).mcpConnections!.find(c => c.name === 'Compact tasks')!.id;
    await expect(row.getByRole('button', { name: 'Manage tools' })).toBeHidden();
    expect((await row.boundingBox())!.height).toBeLessThan(85);
    await work.page.screenshot({ path: info.outputPath('connectors-collapsed.png') });
    await work.page.getByLabel('Search connectors').fill('missing');
    await expect(row).toHaveCount(0);
    await work.page.getByLabel('Search connectors').fill('compact');
    await row.getByRole('button', { name: 'Compact tasks details', exact: true }).click();
    await expect(row.getByRole('button', { name: 'Manage tools' })).toBeVisible();
    await expect(row.getByText(server.url, { exact: true })).toBeVisible();
    await row.getByRole('button', { name: 'Manage tools' }).click();
    await expect(tools).toBeVisible();
    await tools.getByRole('button', { name: 'Close dialog' }).click();
    await row.getByRole('button', { name: 'Compact tasks details', exact: true }).click();
    await expect(row.getByRole('button', { name: 'Remove connection' })).toBeHidden();
    await work.restart();
    await work.page.getByRole('button', { name: 'Settings', exact: true }).click();
    await work.page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Connectors', exact: true }).click();
    const restored = work.page.getByRole('region', { name: 'MCP connection Compact tasks', exact: true });
    await expect(restored.getByRole('button', { name: 'Manage tools' })).toBeHidden();
    await work.page.evaluate(() => window.dextana.setTheme('dark'));
    await work.page.getByRole('button', { name: 'Add connector', exact: true }).click();
    const reopened = work.page.getByRole('dialog', { name: 'Add connector', exact: true });
    await reopened.screenshot({ path: info.outputPath('connectors-add-dark.png') });
    await reopened.getByRole('button', { name: 'Fused', exact: true }).click();
    await expect(reopened.getByRole('button', { name: 'Fused', exact: true })).toHaveAttribute('aria-pressed', 'true');
    await expect(reopened.getByRole('button', { name: 'Custom MCP', exact: true })).toHaveAttribute('aria-pressed', 'false');
    await expect(reopened.getByRole('region', { name: 'Fused workspace', exact: true })).toBeVisible();
    await reopened.screenshot({ path: info.outputPath('connectors-add-fused.png') });
    await reopened.getByRole('button', { name: 'Custom MCP', exact: true }).click();
    await work.page.setViewportSize({ width: 480, height: 720 });
    await expect(reopened).toBeVisible();
    expect(await reopened.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
    await reopened.screenshot({ path: info.outputPath('connectors-add-narrow.png') });
    await work.page.setViewportSize({ width: 1320, height: 880 });
    await work.page.getByRole('button', { name: 'Close add connector' }).click();
    await expect(work.page.getByRole('button', { name: 'Add connector', exact: true })).toBeFocused();
  } finally {
    await work.page.evaluate(() => window.dextana.setTheme('system'));
    if (id) await work.page.evaluate(id => window.dextana.removeMCP(id), id);
    await work.close(); await server.close();
  }
});
