import type { MetaFunction } from '@remix-run/node';
import { BrandLockup, BrandName, FusedLink } from '../Brand';
import { repository } from '../content';

export const meta: MetaFunction = () => [
  { title: 'Getting started — Dextana by Fused' },
  { name: 'description', content: 'Install Dextana, choose your AI, add files, and connect your apps. Practical guides for your first task.' },
];

const sections = [['installation', 'Install Dextana'], ['models', 'Choose your AI'], ['first-task', 'Try a task'], ['context', 'Files and context'], ['integrations', 'Connect your apps'], ['privacy', 'Privacy and permissions'], ['limits', 'Current limits'], ['current-build', 'Current source build']];

export default function Guide() {
  return <>
    <a className="skip-link" href="#main">Skip to guide</a>
    <header className="site-header wrap"><BrandLockup alpha /><a className="text-link" href="/">Back to homepage ↗</a></header>
    <main id="main" className="wrap guide-layout">
      <aside><p className="eyebrow">GETTING STARTED</p><nav aria-label="Guide sections">{sections.map(([id, title]) => <a key={id} href={`#${id}`}>{title}</a>)}</nav></aside>
      <article className="guide-content">
        <h1>A little setup.<br />Then a real task.</h1><p className="guide-intro">Start with <BrandName />, choose the AI you want to use, and give it something useful to do.</p>
        <section id="installation"><h2>Install Dextana</h2>
          <p><a href="/#download">Choose your operating system on the download page</a>, then open the installer package.</p>
          <ul><li><strong>macOS, Apple silicon:</strong> open the DMG, and drag Dextana into Applications.</li><li><strong>Windows, 64-bit:</strong> run the EXE installer.</li><li><strong>Linux, 64-bit:</strong> allow the AppImage to run as a program in your file manager’s permissions, and open it.</li></ul>
          <p>The current alpha packages are not Apple-notarized or Windows verified-publisher releases, so your computer may show a warning. On macOS, after trying to open a trusted build, you can allow it in System Settings → Privacy &amp; Security. Only continue if you recognise and trust the download.</p>
          <p>Installers are public downloads; you do not need a GitHub account. The <a href={`${repository}/releases/tag/desktop-alpha`}>desktop alpha release</a> includes checksums and the tested source revision.</p>
        </section>
        <section id="models"><h2>Choose your AI</h2>
          <p>Dextana is the app that does the work; you choose the AI model it uses. Open <strong>Settings → Models</strong> to connect one. Choose a model that supports tools so it can use the browser and your connected apps.</p>
          <h3>A cloud provider</h3><p>This runs the model with a provider instead of on your computer. You will need the provider’s account details and usually an API key; charges are handled by that provider.</p>
          <ol><li>Choose <strong>OpenAI-compatible</strong> in the Provider field. This is a connection format, so an OpenAI account is not required.</li><li>Enter your provider’s API base URL and API key. For OpenRouter, the address is <code>https://openrouter.ai/api/v1</code>.</li><li>Choose <strong>Fetch models</strong>, select a chat model with tool support, and save. If the provider cannot list its models, enter its exact model ID manually.</li></ol>
          <h3>A model on your computer</h3><p>With Ollama installed and a local model downloaded, choose <strong>Ollama</strong> in Settings. Connect to its address, normally <code>http://127.0.0.1:11434</code>, choose your model, and save. Local processing depends on your computer’s memory and speed. A model labelled as a cloud model still sends work to its provider.</p>
          <p>You can change models for an activity or a follow-up message. For images and browser screenshots, choose a model that supports images as well as tools.</p>
        </section>
        <section id="first-task"><h2>Try a task</h2><p>Describe the result you want, add useful files or links, and include any constraints. For example:</p><blockquote>Use my moving notes and budget to draft a checklist. Keep it within £2,000 and flag anything I still need to decide.</blockquote><p>Choose <strong>Plan</strong> to review the steps first, or <strong>Work</strong> to start. Follow up in the same chat to clarify or change direction. You can also ask Dext to work on independent parts at the same time.</p><p>For reminders or scheduled tasks, specify when they should run. Keep Dextana open and the computer awake. Missed runs are skipped; scheduled tasks still need the usual permissions.</p></section>
        <section id="context"><h2>Files and context</h2><p>Use <strong>Files</strong> beside the message box, or <strong>+</strong> in Context, to select documents. Paste links and instructions into the chat. The Context panel keeps the references together.</p><p>Supported inputs include PDF, Word (.docx), Excel (.xlsx), CSV, text, Markdown, PNG, JPEG, GIF, and WebP. Each file can be up to 5 MB. Scanned PDFs need their text extracted first; image interpretation needs an image-capable model.</p><p>Selecting a file adds its reference. Reading its contents follows the permissions for the action, chat, or approved plan. Ask Dext to create a workbook, CSV, text document, or Markdown file, then use <strong>Show in folder</strong> to find the result. Existing files are not overwritten.</p></section>
        <section id="integrations"><h2>Connect your apps</h2><p><FusedLink /> lets Dext carry out actions in connected services. You can start with browser and file tasks, then add connections when you need them.</p><p>You need a configured <FusedLink /> workspace with the services you want to use. If someone manages it for you, ask them for its connection details. If you are setting it up yourself, the <a href="https://docs.usefused.com/introduction">integration documentation</a> explains the service setup, authentication, and MCP servers that make actions available to Dext.</p><ol><li>Open <strong>Settings → Connectors → Add → <FusedLink /></strong>. Use <strong>Install for Dextana</strong> if the app needs its connection helper.</li><li>Enter your workspace’s Engine address and complete sign-in in the browser.</li><li>Select an available MCP server. Dext tests the connection and discovers its tools during setup.</li><li>Review the tools, choose which to enable and when they need approval, then save their permissions.</li></ol><p>Provider credentials stay in <FusedLink />. You may be asked to approve a temporary access token before the first action. Restricting access to specific operation IDs is optional.</p><details><summary>Already have an MCP connection? <span aria-hidden="true">+</span></summary><p>MCP is a standard way to give an AI app access to tools. In <strong>Settings → Connectors</strong>, add your remote server address or a local tool command. Remote servers need HTTPS and may require a bearer token. Test the connection, review its tools, and enable the ones you need. Only run local commands you trust.</p></details></section>
        <section id="privacy"><h2>Privacy and permissions</h2><p>Chats, plans, file references, and schedules are stored on your computer. A local model processes tasks there; a cloud model receives the conversation and tool content needed for the task, including file references. Websites and connected services receive data needed for their actions.</p><p>In Plan mode, review the steps and resources before approving. The approval covers the plan’s stated scope. In Work mode, you can approve individual actions or allow access for the chat. Connected tools also have their own permission settings. You can revoke automatic chat access with <strong>Ask next time</strong>.</p></section>
        <section id="limits"><h2>Current limits</h2><ul><li>Dextana is a personal desktop workspace. Shared team accounts and collaborative editing are not built in.</li><li>PDF and Word support is for reading. Outputs are Excel workbooks, CSV, text, and Markdown; spreadsheet formulas and macros are not executed.</li><li>The browser can navigate, read, fill forms, and interact with pages. File uploads, browser downloads, and control of other desktop apps are not available.</li><li>Some websites or login checks need your help. Results depend on your selected model and the services you connect. Review important work.</li></ul></section>
        <section id="current-build"><h2>Current source build</h2><p>The <a href={`${repository}/blob/main/README.md#run-from-source`}>developer setup instructions</a> explain how to run the current app. This requires development tools and is separate from installing the packaged alpha. The source repository is public.</p></section>
      </article>
    </main>
    <footer className="site-footer wrap"><BrandLockup /><div className="footer-links"><a href="/">Homepage</a><a href="/#download">Downloads</a><a href="/license.txt">License &amp; usage</a></div></footer>
  </>;
}
